# Generated by Django 3.2.13 on 2023-06-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kopirecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kopirecord',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='kopirecord',
            name='remark',
            field=models.TextField(help_text='Reason of Owing Kopi', verbose_name='remark'),
        ),
    ]
