# Generated by Django 3.2.13 on 2023-12-05 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iteration', '0002_alter_iteration_options'),
        ('kopirecord', '0002_auto_20230614_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='kopirecord',
            name='iteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iteration.iteration'),
        ),
    ]
