# Generated by Django 3.2.13 on 2023-01-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcalendar',
            name='type',
            field=models.CharField(choices=[('Public Holiday', 'Public Holiday'), ('Annual Leave', 'Annual Leave'), ('Medical Leave', 'Medical Leave'), ('Emergency Leave', 'Emergancy Leave'), ('Birthday Leave', 'Birthday Leave')], default='Public Holiday', help_text='Event Type', max_length=16, verbose_name='event type'),
        ),
    ]
