# Generated by Django 3.2.13 on 2023-01-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0002_alter_eventcalendar_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcalendar',
            name='total_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='total days'),
        ),
    ]
