# Generated by Django 3.2.13 on 2023-06-14 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0003_eventcalendar_total_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcalendar',
            options={'ordering': ('-id',)},
        ),
    ]
