# Generated by Django 3.2.13 on 2023-11-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0004_alter_eventcalendar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcalendar',
            name='total_days',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='total days'),
        ),
        migrations.AlterField(
            model_name='eventcalendar',
            name='type',
            field=models.CharField(choices=[('Public Holiday', 'Public Holiday'), ('Annual Leave', 'Annual Leave'), ('Annual Leave AM', 'Annual Leave AM'), ('Annual Leave PM', 'Annual Leave PM'), ('Medical Leave', 'Medical Leave'), ('Emergency Leave', 'Emergancy Leave'), ('Emergency Leave AM', 'Emergancy Leave AM'), ('Emergency Leave PM', 'Emergancy Leave PM'), ('Birthday Leave', 'Birthday Leave')], default='Public Holiday', help_text='Event Type', max_length=18, verbose_name='event type'),
        ),
    ]
