# Generated by Django 3.2.13 on 2022-10-31 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0002_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('hashid', models.CharField(blank=True, editable=False, max_length=16, verbose_name='hashid')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='code')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active. Unselect this instead of deleting.', verbose_name='active')),
                ('create_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='create at')),
                ('update_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='update at')),
                ('name', models.CharField(help_text='Iteration Name', max_length=100, verbose_name='iteration name')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start at')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end at')),
                ('status', models.CharField(choices=[('do', 'do'), ('doing', 'doing'), ('complete', 'complete')], default='do', help_text='status', max_length=16, verbose_name='status')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
