# Generated by Django 3.2.13 on 2023-01-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iteration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteration',
            options={'ordering': ('-id',)},
        ),
    ]
