# Generated by Django 3.2.13 on 2022-11-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('member', 'member')], default='admin', max_length=16, verbose_name='role'),
        ),
    ]
