# Generated by Django 3.2.13 on 2023-01-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='capacity'),
        ),
    ]
