# Generated by Django 3.2.13 on 2023-01-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='capacity'),
        ),
    ]
