# Generated by Django 3.2.13 on 2023-06-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Image', null=True, upload_to='user/image', verbose_name='Image'),
        ),
    ]
