# Generated by Django 3.2.13 on 2023-07-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='capacity'),
        ),
    ]
