# Generated by Django 3.2.13 on 2022-11-02 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_user_role'),
        ('team', '0002_teammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={},
        ),
        migrations.AddField(
            model_name='team',
            name='code',
            field=models.CharField(blank=True, max_length=32, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='team',
            name='create_at',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='hashid',
            field=models.CharField(blank=True, editable=False, max_length=16, verbose_name='hashid'),
        ),
        migrations.AddField(
            model_name='team',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='update_at',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='update at'),
        ),
        migrations.AddField(
            model_name='team',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammember',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this record should be treated as active. Unselect this instead of deleting.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
    ]
