# Generated by Django 3.2.13 on 2023-11-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_teammember_apply_abstract_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_image',
            field=models.ImageField(blank=True, help_text='Team Image', null=True, upload_to='team_images/', verbose_name='Team Image'),
        ),
    ]
