# Generated by Django 3.2.13 on 2025-10-06 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_team_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['team__name', 'user__fullname']},
        ),
    ]
