# Generated by Django 3.2.13 on 2025-10-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='is_live',
        ),
    ]
