# Generated by Django 3.2.13 on 2025-10-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_remove_announcement_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_live',
            field=models.BooleanField(default=True, verbose_name='Is Live'),
        ),
    ]
