# Generated by Django 3.2.13 on 2025-10-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcement_is_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='team',
        ),
    ]
