# Generated by Django 3.2.13 on 2025-11-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20251006_0947'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeasonSession',
            new_name='Season',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='session_name',
            new_name='season_name',
        ),
    ]
