# Generated by Django 3.2.13 on 2022-10-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.CharField(help_text='Description', max_length=100, verbose_name='description name'),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(help_text='Story Name', max_length=100, verbose_name='story name'),
        ),
    ]
