# Generated by Django 3.2.13 on 2022-10-31 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20221031_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='status',
        ),
    ]
