# Generated by Django 3.2.13 on 2022-10-31 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iteration', '0001_initial'),
        ('story', '0003_remove_story_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=100, verbose_name='description name'),
        ),
        migrations.AlterField(
            model_name='story',
            name='iteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iteration.iteration'),
        ),
    ]
