# Generated by Django 3.2.13 on 2022-11-24 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('story', '0004_auto_20221031_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
