# Generated by Django 3.2.13 on 2022-11-29 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_teammember_apply_abstract_model'),
        ('story', '0005_story_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
