# Generated by Django 3.2.13 on 2022-12-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_story_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete')], default='incomplete', help_text='status', max_length=16, verbose_name='status'),
        ),
    ]
