# Generated by Django 3.2.13 on 2022-12-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_story_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='status',
        ),
        migrations.AddField(
            model_name='story',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='is complete'),
        ),
    ]
