# Generated by Django 3.2.13 on 2023-01-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_story_add_is_complete_and_remove_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
    ]
