# Generated by Django 3.2.13 on 2023-01-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_remove_story_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-id',)},
        ),
    ]
