# Generated by Django 3.2.13 on 2023-07-20 09:44

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_story_description_field_change'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(priority='low', then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(priority='normal', then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(priority='high', then=django.db.models.expressions.Value(0)), default=django.db.models.expressions.Value(1), output_field=models.CharField()), '-id']},
        ),
        migrations.AddField(
            model_name='story',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='is delivered'),
        ),
        migrations.AddField(
            model_name='story',
            name='priority',
            field=models.CharField(choices=[('high', 'high'), ('normal', 'normal'), ('low', 'low')], default='normal', max_length=10, verbose_name='priority'),
        ),
    ]
