# Generated by Django 3.2.13 on 2023-11-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_auto_20230720_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_require_tester',
            field=models.BooleanField(default=False, verbose_name='is is_require_tester'),
        ),
    ]
