# Generated by Django 3.2.13 on 2023-11-24 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0013_story_is_require_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='parent_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='story.story'),
        ),
    ]
