# Generated by Django 3.2.13 on 2023-12-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0014_story_add_parent_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_pendingReview',
            field=models.BooleanField(default=False, verbose_name='is pending review'),
        ),
    ]
