# Generated by Django 3.2.13 on 2024-03-26 18:40

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0016_storyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(priority='low', then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(priority='normal', then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(priority='high', then=django.db.models.expressions.Value(0)), default=django.db.models.expressions.Value(1), output_field=models.CharField()), '-id'], 'verbose_name_plural': 'User Stories'},
        ),
    ]
