# Generated by Django 3.2.13 on 2025-10-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0017_alter_story_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_rnd',
            field=models.BooleanField(default=False, help_text='Indicate if story is R&D', verbose_name='is R&D'),
        ),
        migrations.AddField(
            model_name='story',
            name='is_solo',
            field=models.BooleanField(default=False, help_text='Indicate if this story should be done by single user', verbose_name='is solo'),
        ),
        migrations.AddField(
            model_name='story',
            name='need_verify',
            field=models.BooleanField(default=False, help_text='Indicate if story needs verification', verbose_name='need verify'),
        ),
        migrations.AddField(
            model_name='story',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short description of user story', max_length=255, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('new', 'New'), ('started', 'Started'), ('taken', 'Taken'), ('completed', 'Completed')], default='draft', help_text='Current status of the story', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='story',
            name='total_estimate_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='total estimate time'),
        ),
        migrations.AddField(
            model_name='story',
            name='verify_at',
            field=models.DateTimeField(blank=True, help_text='Verification timestamp', null=True, verbose_name='verify at'),
        ),
    ]
