# Generated by Django 3.2.13 on 2025-10-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0018_auto_20251002_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='total_estimate_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total estimated time in hours', max_digits=5, null=True, verbose_name='total estimate time'),
        ),
    ]
