# Generated by Django 3.2.13 on 2025-10-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0019_alter_story_total_estimate_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='is_solo',
        ),
        migrations.AddField(
            model_name='story',
            name='is_multi',
            field=models.BooleanField(default=False, help_text='Indicate if this story should be done by multiple user', verbose_name='is multiple'),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description', verbose_name='description name'),
        ),
    ]
