# Generated by Django 3.2.13 on 2025-10-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0021_verifiedbyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='deployment_production_status_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when deployed to production', null=True, verbose_name='deployed to production at'),
        ),
        migrations.AddField(
            model_name='story',
            name='deployment_staging_status_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when deployed to staging', null=True, verbose_name='deployed to staging at'),
        ),
        migrations.AddField(
            model_name='story',
            name='deployment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('staging', 'Staging'), ('production', 'Production')], default='pending', help_text='Current deployment status', max_length=20, verbose_name='deployment status'),
        ),
        migrations.AddField(
            model_name='story',
            name='has_issue',
            field=models.BooleanField(default=False, help_text='Indicate if this story has deployment or post-deployment issues', verbose_name='has issue'),
        ),
        migrations.AddField(
            model_name='story',
            name='is_needed_to_deploy',
            field=models.BooleanField(default=False, help_text='Indicate if this story requires deployment', verbose_name='is needed to deploy'),
        ),
        migrations.AddField(
            model_name='story',
            name='issue_resolved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when issue was resolved', null=True, verbose_name='issue resolved at'),
        ),
    ]
