# Generated by Django 3.2.13 on 2025-11-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0022_auto_20251021_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completed at'),
        ),
    ]
