# Generated by Django 3.2.13 on 2026-06-24 13:49

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('durian_store', '0002_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('hashid', models.CharField(blank=True, editable=False, max_length=16, verbose_name='hashid')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='code')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active. Unselect this instead of deleting.', verbose_name='active')),
                ('create_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='create at')),
                ('update_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='update at')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-id',),
                'get_latest_by': '-id',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed'), ('bogo', 'Buy 1 Free 1'), ('free_shipping', 'Free Shipping')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_uses',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
