# Generated by Django 3.2.13 on 2022-10-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20221031_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='Task Name', max_length=100, verbose_name='Task name'),
        ),
    ]
