# Generated by Django 3.2.13 on 2022-11-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='used_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='used time'),
        ),
    ]
