# Generated by Django 3.2.13 on 2022-11-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_used_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='used_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='used time'),
        ),
    ]
