# Generated by Django 3.2.13 on 2022-11-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20221122_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
        migrations.AddField(
            model_name='task',
            name='total_hour_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='hour'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Description', null=True, verbose_name='description name'),
        ),
    ]
