# Generated by Django 3.2.13 on 2022-11-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_add_total_hour_used_and_update_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='total_hour_used',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='hour'),
        ),
        migrations.AlterField(
            model_name='taskhour',
            name='hour',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='hour'),
        ),
    ]
