# Generated by Django 3.2.13 on 2023-01-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_set_default_hour_to_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
    ]
