# Generated by Django 3.2.13 on 2023-01-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_remove_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=True, help_text='Description', verbose_name='description name'),
        ),
    ]
