# Generated by Django 3.2.13 on 2023-06-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_task_description_field_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Description', verbose_name='description name'),
        ),
    ]
