# Generated by Django 3.2.13 on 2023-06-19 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iteration', '0002_alter_iteration_options'),
        ('task', '0012_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='iteration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iteration.iteration'),
        ),
    ]
