# Generated by Django 3.2.13 on 2023-06-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_alter_task_iteration'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_bug',
            field=models.BooleanField(default=False, verbose_name='is bug task'),
        ),
    ]
