# Generated by Django 3.2.13 on 2023-10-31 08:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0017_tasktemplate_tasktemplateitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskTemplateItems',
            new_name='TaskTemplateItem',
        ),
    ]
