# Generated by Django 3.2.13 on 2023-11-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_rename_tasktemplateitems_tasktemplateitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplateitem',
            name='description',
            field=models.TextField(help_text='Description', verbose_name='description'),
        ),
    ]
