# Generated by Django 3.2.13 on 2023-11-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_alter_tasktemplateitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplateitem',
            name='estimate_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='estimate time'),
        ),
    ]
