# Generated by Django 3.2.13 on 2023-11-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_tasktemplateitem_estimate_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplateitem',
            name='ordering',
            field=models.PositiveIntegerField(default=1, verbose_name='ordering'),
        ),
    ]
