# Generated by Django 3.2.13 on 2023-12-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_tasktemplateitem_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('do', 'do'), ('doing', 'doing'), ('complete', 'complete'), ('pending review', 'pending review')], default='do', help_text='status', max_length=16, verbose_name='status'),
        ),
    ]
