# Generated by Django 3.2.13 on 2023-12-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('do', 'do'), ('doing', 'doing'), ('complete', 'complete'), ('pending-review', 'pending-review')], default='do', help_text='status', max_length=16, verbose_name='status'),
        ),
    ]
