# Generated by Django 3.2.13 on 2024-01-15 09:14

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_complete',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when={'complete'}),
        ),
    ]
