# Generated by Django 3.2.13 on 2024-01-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_task_status_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status_complete',
            new_name='status_complete_at',
        ),
    ]
