# Generated by Django 3.2.13 on 2025-12-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_rename_status_complete_task_status_complete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhour',
            name='remain_hour',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='remain_hour'),
        ),
    ]
