# Generated by Django 3.2.13 on 2026-01-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_alter_taskhour_remain_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='assigned at'),
        ),
    ]
