# Generated by Django 3.2.13 on 2022-11-24 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_user_role'),
        ('team', '0003_team_teammember_apply_abstract_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('hashid', models.CharField(blank=True, editable=False, max_length=16, verbose_name='hashid')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='code')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active. Unselect this instead of deleting.', verbose_name='active')),
                ('create_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='create at')),
                ('update_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='update at')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
